### ISSUE TITLE
Searching for email

### ISSUE THREAD

**Issue by phavekes** [OpenConext/OpenConext-Invite#325]
When searching for an email address in the users page, I would expect exactly one match. instead all parts of the email entered in the search box seem to be used for matching.

![Image](https://github.com/user-attachments/assets/e4a65c1a-ec5d-4d08-b928-117484a5670d)

**Comment by oharsta** [comment]
InnoDB full-text search does not support the use of the @ symbol in boolean full-text searches. The @ symbol is reserved for use by the @distance proximity search operator. See https://dev.mysql.com/doc/refman/8.4/en/fulltext-boolean.html.

Therefore we have decided to split on the `@` symbol (e.g. replace with a space). Doing not so, would cause the following error for the query string `jdoe@example.com`:
```
java.sql.SQLSyntaxErrorException: (conn=2946) syntax error, unexpected '@', expecting $end
	at org.mariadb.jdbc.export.ExceptionFactory.createException(ExceptionFactory.java:289)
```

Because the `@` is replaced with a space and we don't append `+` symbols, the original query `jdoe@example.com` becomes `jdoe example.com` which is interpreted as a logical `OR`.
  
The correct behaviour would be to tokenise on the `@` symbol and append `+` symbols to the parts. This would transform `jdoe@example.com` into the search string `+jdoe +example.com` which is interpreted as a logical `AND`.

**Comment by oharsta** [comment]
Do note, that the full-text index also tokenises on the `.` symbol. We have to replace `.` occurrences with spaces and prefix the parts with the `+` symbol. For example: input as `john.doe` needs to be transformed to `+john +doe*`

**Comment by MarliesRikken** [comment]
Tested - works as intended now
